// Generated by Flexc++ V2.17.01 on Sun, 22 Mar 2026 20:12:36 +0100

#ifndef Scanner_H_INCLUDED_
#define Scanner_H_INCLUDED_

// $insert baseclass_h
#include "scannerbase.h"

#include <string>


// $insert classHead
class Scanner: public ScannerBase
{
    std::string d_text;
    std::string d_delim;
    
    size_t d_stringCount = 0;
    
    public:
        explicit Scanner(std::istream &in = std::cin, 
                        std::ostream &out = std::cout, bool keepCwd = true);

        Scanner(std::string const &infile, std::string const &outfile, 
                                                        bool keepCwd = true);
        
        // $insert lexFunctionDecl
        int lex();
        std::string const &text();
        std::string stringAlt();

    private:
        void count();
        size_t stringNr();
        
        void addToText();
        void setDelim();
        void clearText();
        void clearDelim();
        
        void foundString();
        void delim();
        void rsl();
        
        int lex_();
        int executeAction_(size_t ruleNr);

        void print();
        void preCode();     // re-implement this function for code that must 
                            // be exec'ed before the patternmatching starts

        void postCode(PostEnum_ type);    
                            // re-implement this function for code that must 
                            // be exec'ed after the rules's actions.
};

// $insert scannerConstructors
inline Scanner::Scanner(std::istream &in, std::ostream &out, bool keepCwd)
:
    ScannerBase(in, out, keepCwd)
{}

inline Scanner::Scanner(std::string const &infile, 
                                    std::string const &outfile, bool keepCwd)
:
    ScannerBase(infile, outfile, keepCwd)
{}

// $insert inlineLexFunction
inline int Scanner::lex()
{
    return lex_();
}

inline std::string const &Scanner::text()
{
    return d_text;
}

inline void Scanner::count()
{
    ++d_stringCount;
}

inline size_t Scanner::stringNr()
{
    return d_stringCount;
}

inline void Scanner::addToText()
{
    d_text += matched();
}

inline void Scanner::setDelim()
{
    d_delim = matched().substr(0, matched().size() - 1);
}

inline void Scanner::clearText()
{
    d_text.clear();
}

inline void Scanner::clearDelim()
{
    d_delim.clear();
}

inline void Scanner::preCode() 
{
    // optionally replace by your own code
}

inline void Scanner::postCode([[maybe_unused]] PostEnum_ type) 
{
    // optionally replace by your own code
}

inline void Scanner::print() 
{
    print_();
}


#endif // Scanner_H_INCLUDED_

