// Generated by Bisonc++ V6.04.03 on Fri, 15 Apr 2022 13:49:59 +0200

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
#include "parserbase.h"
// $insert scanner.h
#include "../scanner/scanner.h"

#include "../rules/rules.h"

class Parser: public ParserBase
{
    // $insert scannerobject
    Scanner d_scanner;
    Rules d_rules;
    
    public:
        Parser() = default;
        int parse();
        
        Rules const &rules() const;

    private:
                                        // called on (syntax) errors
        void error();    
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc
        void exceptionHandler(std::exception const &exc);

    // support functions for parse():
        void executeAction_(int ruleNr);
        void errorRecovery_();
        void nextCycle_();
        void nextToken_();
        void print_();

    // grammar parsing functions:
        void storeRules(RuleValue const &item1, RuleValue const &item3);
};

inline Rules const &Parser::rules() const
{
    return d_rules;
}

#endif
