// Generated by Bisonc++ V6.04.03 on Fri, 15 Apr 2022 13:49:59 +0200

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
#include "parserbase.h"
// $insert scanner.h
#include "../scanner/scanner.h"

#include <string>

class Parser: public ParserBase
{
    // $insert scannerobject
    Scanner d_scanner;

    bool d_display;
        
    public:
        Parser();
        int parse();

    private:
                                        // called on (syntax) errors
        void error();    
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc
        void exceptionHandler(std::exception const &exc);

    // added functions for the calculator:

        void display(double &expr);
        void done();
        void prompt();

        double add(double &lvalue, double &rvalue) const;
        double sub(double &lvalue, double &rvalue) const;
        double mul(double &lvalue, double &rvalue) const;
        double div(double &lvalue, double &rvalue) const;
        
        double negate(double &expr) const;
        double value();
        
    // support functions for parse():
        void executeAction_(int ruleNr);
        void errorRecovery_();
        void nextCycle_();
        void nextToken_();
        void print_();
};


#endif
