// Generated by Bisonc++ V6.04.03 on Fri, 15 Apr 2022 13:49:59 +0200

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
#include "parserbase.h"
// $insert scanner.h
#include "../scanner/scanner.h"

#include "../functions/functions.h"

#include <vector>
#include <unordered_map>
#include <string>


class Parser: public ParserBase
{
    // $insert scannerobject
    Scanner d_scanner;

    std::vector<double> d_value;
    std::unordered_map<std::string, unsigned> d_symtab;
    
    Functions d_functions;

    bool d_display;
        
    public:
        Parser(bool run);
        int parse();

    private:
                                        // called on (syntax) errors
        void error(char const *msg = "syntax error");    
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc
        void exceptionHandler(std::exception const &exc);

    // support functions for parse():
        void executeAction_(int ruleNr);
        void errorRecovery_();
        void nextCycle_();
        void nextToken_();
        void print_();

    // added functions for the calculator:

        void display(RuleValue &expr);
        void done();
        void prompt();
        
        RuleValue callFunction(std::string const &name, 
                                            Functions::ArgVec const &args);

        RuleValue add(RuleValue &lvalue, RuleValue &rvalue) const;
        RuleValue sub(RuleValue &lvalue, RuleValue &rvalue) const;
        RuleValue negate(RuleValue &expr) const;
        RuleValue &assign(RuleValue &lvalue, RuleValue &rvalue);
        
        RuleValue value();
        RuleValue variable();
        RuleValue function();
        
        RuleValue e_const() const;
        RuleValue pi_const() const;

        double valueOf(RuleValue const &expr) const;
};

inline RuleValue Parser::e_const() const
{
    return RuleValue{2.71828};
}

inline RuleValue Parser::pi_const() const
{
    return RuleValue{3.14159};
}

#endif
