// Generated by Bisonc++ V6.04.03 on Fri, 15 Apr 2022 13:49:59 +0200

#ifndef Parser_h_included
#define Parser_h_included

// $insert baseclass
#include "parserbase.h"
// $insert scanner.h
#include "../scanner/scanner.h"

#include <vector>
#include <unordered_map>
#include <string>

class Parser: public ParserBase
{
    // angle mechanics:
    enum class AngleMode
    {
        RAD,
        DEG,
        GRAD
    };
    
    // currently used angle type, initialised as radians:
    AngleMode d_angleMode = AngleMode::RAD;
    
    // $insert scannerobject
    Scanner d_scanner;

    std::vector<double> d_value;
    std::unordered_map<std::string, unsigned> d_symtab;

    bool d_display;
        
    public:
        Parser(bool run);
        int parse();

    private:
                                        // called on (syntax) errors
        void error(char const *msg = "syntax error");    
        int lex();                      // returns the next token from the
                                        // lexical scanner. 
        void print();                   // use, e.g., d_token, d_loc
        void exceptionHandler(std::exception const &exc);

    // support functions for parse():
        void executeAction_(int ruleNr);
        void errorRecovery_();
        void nextCycle_();
        void nextToken_();
        void print_();

    // added functions for the calculator:

        void display(RuleValue &expr);
        void done();
        void prompt();

        RuleValue add(RuleValue &lvalue, RuleValue &rvalue) const;
        RuleValue sub(RuleValue &lvalue, RuleValue &rvalue) const;
        RuleValue negate(RuleValue &expr) const;
        RuleValue &assign(RuleValue &lvalue, RuleValue &rvalue);
        
        RuleValue value();
        RuleValue variable();
        
        RuleValue sin(RuleValue &expr) const;
        RuleValue asin(RuleValue &expr);
        RuleValue cos(RuleValue &expr) const;
        RuleValue acos(RuleValue &expr);
        RuleValue tan(RuleValue &expr) const;
        RuleValue atan(RuleValue &expr);
        
        RuleValue abs(RuleValue &expr) const;
        RuleValue exp(RuleValue &expr) const;
        RuleValue ln(RuleValue &expr);
        RuleValue sqrt(RuleValue &expr);
        
        void math_error(char const *msg);
        
        RuleValue e_const() const;
        RuleValue pi_const() const;

        double valueOf(RuleValue const &expr) const;
    
    // support functions for angles
        void set_angle_mode(AngleMode mode);
        double to_radians(double value) const;
        double from_radians(double value) const;
};

inline RuleValue Parser::exp(RuleValue &expr) const
{
    return RuleValue{ std::exp(valueOf(expr)) };
}

inline RuleValue Parser::sin(RuleValue &expr) const
{
    return RuleValue{ std::sin(to_radians(valueOf(expr))) };
}

inline RuleValue Parser::cos(RuleValue &expr) const
{    
    return RuleValue{ std::cos(to_radians(valueOf(expr))) };
}

inline RuleValue Parser::tan(RuleValue &expr) const
{    
    return RuleValue{ std::tan(to_radians(valueOf(expr))) };
}

inline RuleValue Parser::abs(RuleValue &expr) const
{
    return RuleValue{ std::fabs(valueOf(expr)) };
}

inline RuleValue Parser::e_const() const
{
    return RuleValue{2.71828};
}

inline RuleValue Parser::pi_const() const
{
    return RuleValue{3.14159};
}

inline void Parser::set_angle_mode(AngleMode mode)
{
    d_angleMode = mode;
}

#endif
