// Generated by Flexc++ V2.19.00 on Thu, 16 Apr 2026 13:47:48 +0200

#include <iostream>
#include <fstream>
#include <sstream>
#include <stdexcept>
#include <filesystem>

// $insert class_ih
#include "scanner.ih"


    // s_ranges_: use (unsigned) characters as index to obtain
    //           that character's range-number.
    //           The range for EOF is defined in a constant in the
    //           class header file
size_t const ScannerBase::s_ranges_[] =
{
     0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
     3, 3, 3, 3, 3, 3, 3, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 7, 8, 9,10,11,11,
    11,11,11,11,11,11,11,11,12,12,12,12,12,12,12,13,13,13,13,14,15,15,15,15,15,
    15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,16,16,16,16,17,18,19,20,21,
    22,23,24,25,26,27,28,28,29,30,31,32,33,34,35,36,37,38,39,39,40,41,41,42,42,
    42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,
    42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,
    42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,
    42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,
    42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,42,
    42,42,42,42,42,42,
};

// $insert startcondinfo
    // s_dfa_ contains the rows of *all* DFAs ordered by start state.  The
    // enum class StartCondition_is defined in the baseclass header.
    // StartCondition_::INITIAL is always 0.  Each entry defines the row to
    // transit to if the column's character range was sensed. Row numbers are
    // relative to the used DFA, and d_dfaBase_ is set to the first row of
    // the subset to use.  The row's final two values are respectively the
    // rule that may be matched at this state, and the rule's FINAL flag. If
    // the final value equals FINAL (= 1) then, if there's no continuation,
    // the rule is matched. If the BOL flag (8) is also set (so FINAL + BOL (=
    // 9) is set) then the rule only matches when d_atBOL is also true.
int const ScannerBase::s_dfa_[][46] =
{
    // INITIAL
    { 1, 2, 1, 1, 2, 1, 1, 1, 1, 3, 1, 4, 1, 5, 5, 5, 1, 5, 1, 6,
          5, 7, 8, 9, 5,10, 5, 5, 5,11, 5, 5, 5,12,13,14,15,16, 5, 5,
          5, 5, 1,-1,    -1, -1},  // 0
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,    20, -1},  // 1
    {-1, 2,-1,-1, 2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,     0, -1},  // 2
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,17,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,    20, -1},  // 3
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,18,-1, 4,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,     1, -1},  // 4
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 5
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5,19, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,20,21, 5, 5,
          5, 5,-1,-1,    19, -1},  // 6
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,22, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 7
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5,23, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 8
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
         24, 5,-1,-1,     5, -1},  // 9
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,25, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 10
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,26, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 11
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5,27, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 12
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,28, 5,
          5, 5,-1,-1,    19, -1},  // 13
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1,29,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 14
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5,30, 5, 5, 5, 5, 5, 5,31, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 15
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1,32,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 16
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,17,-1,-1,33,-1,-1,-1,-1,-1,
         -1,-1,-1,33,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,     3, -1},  // 17
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,34,-1,-1,35,-1,-1,-1,-1,-1,
         -1,-1,-1,35,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,     2, -1},  // 18
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,36, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 19
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5,37, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 20
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1,38,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 21
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,39, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 22
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5,40, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 23
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5,41, 5, 5, 5, 5, 5,42, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 24
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1,43,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 25
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,     6, -1},  // 26
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,     4, -1},  // 27
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5,44, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 28
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5,45, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 29
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,46, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 30
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,47, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 31
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,48, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 32
    {-1,-1,-1,-1,-1,-1,49,-1,49,-1,-1,50,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,    -1, -1},  // 33
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,34,-1,-1,51,-1,-1,-1,-1,-1,
         -1,-1,-1,51,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,     2, -1},  // 34
    {-1,-1,-1,-1,-1,-1,52,-1,52,-1,-1,53,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,    -1, -1},  // 35
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,54, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 36
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,55, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 37
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,56, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 38
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    12, -1},  // 39
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    16, -1},  // 40
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,57, 5, 5,
          5, 5,-1,-1,    19, -1},  // 41
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,     7, -1},  // 42
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5,58, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    19, -1},  // 43
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,57, 5, 5,
          5, 5,-1,-1,    19, -1},  // 44
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    15, -1},  // 45
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    10, -1},  // 46
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,59, 5, 5,
          5, 5,-1,-1,    19, -1},  // 47
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    14, -1},  // 48
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,50,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,    -1, -1},  // 49
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,50,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,     3, -1},  // 50
    {-1,-1,-1,-1,-1,-1,60,-1,60,-1,-1,61,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,    -1, -1},  // 51
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,53,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,    -1, -1},  // 52
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,53,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,     2, -1},  // 53
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    11, -1},  // 54
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,     9, -1},  // 55
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    13, -1},  // 56
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    18, -1},  // 57
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,    17, -1},  // 58
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1, 5,-1, 5, 5, 5,-1, 5,-1, 5,
          5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
          5, 5,-1,-1,     8, -1},  // 59
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,61,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,    -1, -1},  // 60
    {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,61,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,
         -1,-1,-1,-1,     2, -1},  // 61
};


int const (*ScannerBase::s_dfaBase_[])[46] =
{
    s_dfa_ + 0,
};

size_t ScannerBase::s_istreamNr = 0;

// $insert inputImplementation
ScannerBase::Input::Input()
:
    d_in(0),
    d_lineNr(1)
{}

ScannerBase::Input::Input(std::istream *iStream, size_t lineNr)
:
    d_in(iStream),
    d_lineNr(lineNr)
{}

size_t ScannerBase::Input::get()
{
    switch (size_t ch = next())         // get the next input char
    {
        case '\n':
            ++d_lineNr;
        [[fallthrough]];

        default:
        return ch;
    }
}

size_t ScannerBase::Input::next()
{
    size_t ch;

    if (d_deque.empty())                // deque empty: next char fm d_in
    {
        if (d_in == 0)
            return AT_EOF;
        ch = d_in->get();
        return *d_in ? ch : static_cast<size_t>(AT_EOF);
    }

    ch = d_deque.front();
    d_deque.pop_front();

    return ch;
}

void ScannerBase::Input::reRead(size_t ch)
{
    if (ch < 0x100)
    {
        if (ch == '\n')
            --d_lineNr;
        d_deque.push_front(ch);
    }
}

void ScannerBase::Input::reRead(std::string const &str, size_t fm)
{
    for (size_t idx = str.size(); idx-- > fm; )
        reRead(str[idx]);
}

ScannerBase::ScannerBase(std::istream &in, std::ostream &out, bool keepCwd)
:
    d_out(new std::ostream(out.rdbuf())),
// $insert interactiveInit
    d_in(&in),
    d_line(new std::istringstream()),
    d_dfaBase_(s_dfa_)
{
    if (keepCwd)
        d_cwd = std::filesystem::current_path().string();
    p_pushStream(s_istream, new std::istream(d_line->rdbuf()));
}

void ScannerBase::switchStream_(std::istream &in, size_t lineNr)
{
    d_input->close();
    d_streamStack.back().input = { new std::istream(in.rdbuf()), lineNr };
}



void ScannerBase::toCwd() const
{
    using namespace std;
    using namespace filesystem;

    if (d_cwd.empty())
        return;

    error_code ec;
    current_path(d_cwd, ec);
}

// static
std::string ScannerBase::chgWorkingDir(std::string const &name)     // any name
{
    using namespace std;
    using namespace filesystem;

    if (name == s_istream)                              // used with istreams
        return name;
                                                        // a filename: get its
    auto path = absolute(name);                         // full pathname

    error_code ec;
    current_path(path.parent_path(), ec);

    return path.string();                               // return the pathname
}

void ScannerBase::p_pushStream(std::string const &name, std::istream *streamPtr)
{
    if (d_streamStack.size() == s_maxSizeofStreamStack_)
    {
        delete streamPtr;
        throw std::length_error("Max stream stack size exceeded");
    }

    d_filename = name;
    d_streamStack.push_back(
                    StreamStruct{chgWorkingDir(d_filename), { streamPtr } }
                  );

    d_input = &d_streamStack.back().input;

    d_atBOL = true;
}

void ScannerBase::switchOstream(std::ostream &out)
{
    *d_out << std::flush;
    d_out.reset(new std::ostream(out.rdbuf()));
}

// $insert debugFunctions
void ScannerBase::setDebug(bool onOff)
{}

bool ScannerBase::debug() const
{
    return false;
}

void ScannerBase::redo(size_t nChars)
{
    size_t from = nChars >= length() ? 0 : length() - nChars;
    d_input->reRead(d_matched, from);
    d_matched.resize(from);
}

void ScannerBase::switchOstream(std::string const &outfilename)
{
    *d_out << std::flush;
    d_out.reset(
            outfilename == "-"    ? new std::ostream(std::cout.rdbuf()) :
            outfilename == ""     ? new std::ostream(std::cerr.rdbuf()) :
                                    new std::ofstream(outfilename));
}


bool ScannerBase::popStream()
{
    using namespace std::filesystem;

    d_input->close();

    if (d_streamStack.size() <= 1)
        return false;

    d_streamStack.pop_back();

    d_filename = path{ chgWorkingDir(d_streamStack.back().pushedName) 
                     }.filename().string();

    d_input = &d_streamStack.back().input;

    return true;
}



  // See the manual's section `Run-time operations' section for an explanation
  // of this member.
ScannerBase::ActionType_ ScannerBase::actionType_(size_t range)
{
    d_nextState = d_dfaBase_[d_state][range];

    if (d_nextState != -1)                  // transition is possible
        return ActionType_::CONTINUE;

    if (knownFinalState())                  // FINAL state reached
        return ActionType_::MATCH;         

    if (d_matched.size())
        return ActionType_::ECHO_FIRST;    // no match, echo the 1st char

    return range != s_rangeOfEOF_ ? 
                ActionType_::ECHO_CH 
            : 
                ActionType_::RETURN;
}

void ScannerBase::accept(size_t nChars)          // old name: less
{
    if (nChars < d_matched.size())
    {
        d_input->reRead(d_matched, nChars);
        d_matched.resize(nChars);
    }
}

void ScannerBase::setMatchedSize(size_t length)
{
    d_input->reRead(d_matched, length);  // reread the tail section
    d_matched.resize(length);           // return what's left
}

  // At this point a rule has been matched.  The next character is not part of
  // the matched rule and is sent back to the input.  The final match length
  // is determined, the index of the matched rule is determined, and then
  // d_atBOL is updated. Finally the rule's index is returned.
  // The numbers behind the finalPtr assignments are explained in the 
  // manual's `Run-time operations' section.
size_t ScannerBase::matched_(size_t ch)
{
    d_input->reRead(ch);

    FinalData *finalPtr;
                            
    if (not d_atBOL)                    // not at BOL
        finalPtr = &d_final.std;        // then use the std rule (3, 4)

                                        // at BOL
    else if (not available(d_final.std.rule))   // only a BOL rule avail.
            finalPtr = &d_final.bol;            // use the BOL rule (6)

    else if (not available(d_final.bol.rule)) // only a std rule is avail.
        finalPtr = &d_final.std;        // use the std rule (7)
        
    else if (                           // Both are available (8)
        d_final.bol.length !=           // check lengths of matched texts
        d_final.std.length              // unequal lengths, use the rule
    )                                   // having the longer match length
        finalPtr =              
            d_final.bol.length > d_final.std.length ?
                &d_final.bol
            :
                &d_final.std;

    else                            // lengths are equal: use 1st rule
        finalPtr = 
            d_final.bol.rule < d_final.std.rule ?
                &d_final.bol
            :
                &d_final.std;

    setMatchedSize(finalPtr->length);

                                // size check needed since g++-15
    d_atBOL = d_matched.size() > 0 and d_matched.back() == '\n';


    return finalPtr->rule;
}

size_t ScannerBase::getRange_(int ch)       // using int to prevent casts
{
    return ch == AT_EOF ? as<size_t>(s_rangeOfEOF_) : s_ranges_[ch];
}

  // At this point d_nextState contains the next state and continuation is
  // possible. The just read char. is appended to d_match
void ScannerBase::continue_(int ch)
{
    d_state = d_nextState;

    if (ch != AT_EOF)
        d_matched += ch;
}

void ScannerBase::echoCh_(size_t ch)
{
    *d_out << as<char>(ch);
    d_atBOL = ch == '\n';
}


   // At this point there is no continuation. The last character is
   // pushed back into the input stream as well as all but the first char. in
   // the buffer. The first char. in the buffer is echoed to stderr. 
   // If there isn't any 1st char yet then the current char doesn't fit any
   // rules and that char is then echoed
void ScannerBase::echoFirst_(size_t ch)
{
    d_input->reRead(ch);
    d_input->reRead(d_matched, 1);
    echoCh_(d_matched[0]);
}

    // Update the rules associated with the current state, do this separately
    // for BOL and std rules.
    // If a rule was set, update the rule index and the current d_matched
    // length. 
void ScannerBase::updateFinals_()
{
    size_t len = d_matched.size();

    int const *rf = d_dfaBase_[d_state] + s_finIdx_;

    if (rf[0] != -1)        // update to the latest std rule
    {
        d_final.std = FinalData { as<size_t>(rf[0]), len };
    }

    if (rf[1] != -1)        // update to the latest bol rule
    {
        d_final.bol = FinalData { as<size_t>(rf[1]), len };
    }
}

void ScannerBase::reset_()
{
    d_final = Final{ 
                    FinalData{s_unavailable, 0}, 
                    FinalData {s_unavailable, 0} 
                };

    d_state = 0;
    d_return = true;

    if (!d_more)
        d_matched.clear();

    d_more = false;
}

int Scanner::executeAction_(size_t ruleIdx)
try
{
    switch (ruleIdx)
    {
        // $insert actions
        case 1:
        case 2:
        case 3:
        {
#line 16 "lexer"
            return Tokens::NUMBER;
        }
        break;
        case 4:
        {
#line 18 "lexer"
            return Tokens::PI_CONST;
        }
        break;
        case 5:
        {
#line 19 "lexer"
            return Tokens::E_CONST;
        }
        break;
        case 6:
        {
#line 21 "lexer"
            return Tokens::LN;
        }
        break;
        case 7:
        {
#line 22 "lexer"
            return Tokens::EXP;
        }
        break;
        case 8:
        {
#line 23 "lexer"
            return Tokens::SQRT;
        }
        break;
        case 9:
        {
#line 25 "lexer"
            return Tokens::ASIN;
        }
        break;
        case 10:
        {
#line 26 "lexer"
            return Tokens::SIN;
        }
        break;
        case 11:
        {
#line 27 "lexer"
            return Tokens::ACOS;
        }
        break;
        case 12:
        {
#line 28 "lexer"
            return Tokens::COS;
        }
        break;
        case 13:
        {
#line 29 "lexer"
            return Tokens::ATAN;
        }
        break;
        case 14:
        {
#line 30 "lexer"
            return Tokens::TAN;
        }
        break;
        case 15:
        {
#line 32 "lexer"
            return Tokens::RAD;
        }
        break;
        case 16:
        {
#line 33 "lexer"
            return Tokens::DEG;
        }
        break;
        case 17:
        {
#line 34 "lexer"
            return Tokens::GRAD;
        }
        break;
        case 18:
        {
#line 36 "lexer"
            return Tokens::EXIT;
        }
        break;
        case 19:
        {
#line 38 "lexer"
            return Tokens::IDENT;
        }
        break;
        case 20:
        {
#line 40 "lexer"
            return matched().front();
        }
        break;
    }
    noReturn_();
    return 0;
}
catch (Leave_ value)
{
    return static_cast<int>(value);
}

int Scanner::lex_()
{
    reset_();
    preCode();

    while (true)
    {
        size_t ch = get_();                // fetch next char
        size_t range = getRange_(ch);      // determine the range

        updateFinals_();                    // update the state's Final info

        switch (actionType_(range))        // determine the action
        {
            case ActionType_::CONTINUE:
                continue_(ch);
            continue;

            case ActionType_::MATCH:
            {
                d_token_ = executeAction_(matched_(ch));
                if (return_())
                {
                    print();
                    toCwd();
                    return d_token_;
                }
                break;
            }

            case ActionType_::ECHO_FIRST:
                echoFirst_(ch);
            break;

            case ActionType_::ECHO_CH:
                echoCh_(ch);
            break;

            case ActionType_::RETURN:
                if (!popStream())
                {
                     postCode(PostEnum_::END);
                     toCwd();
                     return 0;
                }
                postCode(PostEnum_::POP);
             continue;
        } // switch

        postCode(PostEnum_::WIP);

        reset_();
        preCode();
    } // while
}

void ScannerBase::print_() const
{
}

// $insert interactiveLex
bool ScannerBase::interactiveLine()
{
    std::string line;

    if (not std::getline(*d_in, line))
        return false;

    line += '\n';
    d_line->clear();
    d_line->str(line);
    switchStream_(*d_line, lineNr());

    return true;
}

int Scanner::lex()
{
    return lex_() != 0        ? d_token_ :
           interactiveLine() ?   lex_()   :
                                 0;
}

