// Generated by Flexc++ V2.17.01 on Mon, 23 Mar 2026 15:02:12 +0100

#ifndef Scanner_H_INCLUDED_
#define Scanner_H_INCLUDED_

// $insert baseclass_h
#include "scannerbase.h"


// $insert classHead
class Scanner: public ScannerBase
{
    std::string d_line;
    
    size_t d_shift = 0;
    
    size_t d_idents = 0;
    size_t d_ints = 0;
    size_t d_doubles = 0;
    size_t d_chars = 0;
    
    public:
        enum Tokens
        {
            NEWLINE = 265
        };
        
        explicit Scanner(std::istream &in = std::cin, 
                        std::ostream &out = std::cout, bool keepCwd = true);

        Scanner(std::string const &infile, 
                            std::string const &outfile, bool keepCwd = true);
        
        // $insert lexFunctionDecl
        int lex();
        
        std::string const &line() const;
        
        size_t lineNr() const;      // custom accessor
        void showCounts() const;

    private:
        void append();
        void clear();
        
        void countIdent();
        void countInt();
        void countDouble();
        void countChar();
        
        void setShift();
        
        void newline();
        
        int lex_();
        int executeAction_(size_t ruleNr);

        void print();
        void preCode();     // re-implement this function for code that must 
                            // be exec'ed before the patternmatching starts

        void postCode(PostEnum_ type);    
                            // re-implement this function for code that must 
                            // be exec'ed after the rules's actions.
};

// $insert scannerConstructors
inline Scanner::Scanner(std::istream &in, std::ostream &out, bool keepCwd)
:
    ScannerBase(in, out, keepCwd)
{}

inline Scanner::Scanner(std::string const &infile, 
                                    std::string const &outfile, bool keepCwd)
:
    ScannerBase(infile, outfile, keepCwd)
{}

// $insert inlineLexFunction
inline int Scanner::lex()
{
    return lex_();
}

inline std::string const &Scanner::line() const
{
    return d_line;
}

inline size_t Scanner::lineNr() const           // accessor
{
    return ScannerBase::lineNr() + d_shift;
}

inline void Scanner::append()
{
    d_line += matched();
}

inline void Scanner::clear()
{
    d_line.clear();
}

inline void Scanner::countIdent()
{
    ++d_idents;
}

inline void Scanner::countInt()
{
    ++d_ints;
}

inline void Scanner::countDouble()
{
    ++d_doubles;
}

inline void Scanner::countChar()
{
    ++d_chars;
}

inline void Scanner::preCode() 
{
    // optionally replace by your own code
}

inline void Scanner::postCode([[maybe_unused]] PostEnum_ type) 
{
    // optionally replace by your own code
}

inline void Scanner::print() 
{
    print_();
}


#endif // Scanner_H_INCLUDED_

